# Generated by Django 5.1.4 on 2026-09-25 16:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apix', '0002_extensions_and_hypertables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canonicalfare',
            name='flags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('PARTIAL_BREAKDOWN', 'Total present, components missing'), ('COMPONENT_DERIVED', 'One component derived as residual'), ('TOTAL_DERIVED', 'Total derived from components'), ('TOTAL_MISMATCH', 'Components do not reconcile to total'), ('EXPLICIT_ZERO', 'A component is genuinely zero (waived)'), ('SOLD_OUT', 'Inventory exhausted - fare is NULL by rule'), ('OUTLIER_HIGH', 'Modified Z-score above threshold'), ('OUTLIER_LOW', 'Modified Z-score below negative threshold'), ('DUPLICATE_SUPPRESSED', 'Lost cross-source dedup tie-break'), ('CROSS_SOURCE_CONFLICT', 'Sources disagree on price'), ('STALE_OBSERVATION', 'Observed outside the collection window'), ('MODELLED', 'Imputed / modelled, not directly observed'), ('COMPONENT_UNPARSEABLE', 'A component value was corrupt or unparseable'), ('PRICE_UNAVAILABLE', 'Offered but price not published')], max_length=32), blank=True, default=list, size=None),
        ),
    ]
